# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jslint-johnson}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["William Howard"]
  s.date = %q{2011-06-28}
  s.default_executable = %q{jslint-johnson}
  s.description = %q{    - Ruby gem wrapper for a JSLint CLI.
    - Uses the Johnson library for performance.
    - Targeted for usage in CI environments.
    - Thoroughly tested.
}
  s.email = %q{whoward.tke@gmail.com}
  s.executables = ["jslint-johnson"]
  s.homepage = %q{http://github.com/whoward/jslint-johnson}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.1}
  s.summary = %q{JSLint CLI and rake tasks via johnson}
  s.test_files = [
    "test/helper.rb",
    "test/suite.rb",
    "test/test_cli.rb",
    "test/test_formatter.rb",
    "test/test_lint_error.rb",
    "test/test_runner.rb",
    "test/test_task.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<johnson>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_runtime_dependency(%q<johnson>, ["~> 1.2.0"])
    else
      s.add_dependency(%q<johnson>, ["~> 1.2.0"])
      s.add_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_dependency(%q<johnson>, ["~> 1.2.0"])
    end
  else
    s.add_dependency(%q<johnson>, ["~> 1.2.0"])
    s.add_dependency(%q<rake>, ["~> 0.8.7"])
    s.add_dependency(%q<johnson>, ["~> 1.2.0"])
  end
end

